-- Enterprise Identity Digital Twin Platform — Prompt 199
CREATE SCHEMA IF NOT EXISTS identity_twin;
CREATE TABLE IF NOT EXISTS identity_twin.digital_twins (tenant_id VARCHAR(63) NOT NULL, id UUID NOT NULL, twin_ref VARCHAR(64) NOT NULL, identity_ref VARCHAR(128) NOT NULL, attributes JSONB NOT NULL DEFAULT '{}', role_refs JSONB NOT NULL DEFAULT '[]', session_refs JSONB NOT NULL DEFAULT '[]', federation_link_refs JSONB NOT NULL DEFAULT '[]', lifecycle_state VARCHAR(64), source_versions JSONB NOT NULL DEFAULT '{}', updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (tenant_id, id), UNIQUE (tenant_id, twin_ref), UNIQUE (tenant_id, identity_ref));
CREATE INDEX IF NOT EXISTS idx_twin_identity ON identity_twin.digital_twins(tenant_id, identity_ref);
CREATE TABLE IF NOT EXISTS identity_twin.twin_snapshots (tenant_id VARCHAR(63) NOT NULL, id UUID NOT NULL, snapshot_ref VARCHAR(64) NOT NULL, twin_ref VARCHAR(64) NOT NULL, projection JSONB NOT NULL, source_event VARCHAR(128) NOT NULL, captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (tenant_id, id), UNIQUE (tenant_id, snapshot_ref));
CREATE INDEX IF NOT EXISTS idx_twin_snapshots_twin ON identity_twin.twin_snapshots(tenant_id, twin_ref, captured_at DESC);
CREATE TABLE IF NOT EXISTS identity_twin.twin_simulations (tenant_id VARCHAR(63) NOT NULL, id UUID NOT NULL, simulation_ref VARCHAR(64) NOT NULL, twin_ref VARCHAR(64) NOT NULL, scenario_type VARCHAR(64) NOT NULL, proposed_change JSONB NOT NULL DEFAULT '{}', outcome JSONB NOT NULL DEFAULT '{}', status VARCHAR(32) NOT NULL DEFAULT 'completed', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (tenant_id, id), UNIQUE (tenant_id, simulation_ref));
CREATE INDEX IF NOT EXISTS idx_twin_simulations_twin ON identity_twin.twin_simulations(tenant_id, twin_ref, created_at DESC);
CREATE TABLE IF NOT EXISTS identity_twin.twin_drift_alerts (tenant_id VARCHAR(63) NOT NULL, id UUID NOT NULL, alert_ref VARCHAR(64) NOT NULL, twin_ref VARCHAR(64) NOT NULL, source_event VARCHAR(128) NOT NULL, drift_fields JSONB NOT NULL DEFAULT '[]', severity VARCHAR(16) NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'open', detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (tenant_id, id), UNIQUE (tenant_id, alert_ref));
CREATE INDEX IF NOT EXISTS idx_twin_drift_open ON identity_twin.twin_drift_alerts(tenant_id, status, severity, detected_at DESC);
