"""Plugin repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.plugins.domain.aggregates.plugin import Plugin, PluginInstallation


class IPluginRepository(Protocol):
    async def save(self, plugin: Plugin) -> None: ...
    async def find_by_id(self, plugin_id: str) -> Plugin | None: ...
    async def list_all(self) -> list[Plugin]: ...
    async def list_by_type(self, plugin_type: str) -> list[Plugin]: ...
    async def search(self, query: str) -> list[Plugin]: ...


class IPluginInstallationRepository(Protocol):
    async def save(self, installation: PluginInstallation) -> None: ...
    async def find(self, tenant_id: str, plugin_id: str) -> PluginInstallation | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[PluginInstallation]: ...
    async def delete(self, tenant_id: str, plugin_id: str) -> bool: ...
