"""Directory repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.directory.domain.aggregates.directory_platform import (
    DirectoryProfile,
    DirectorySyncJob,
    LdapConnector,
    SamlProvider,
    ScimProvider,
)


class IDirectoryProfileRepository(Protocol):
    async def find_by_tenant(self, tenant_id: str) -> DirectoryProfile | None: ...
    async def save(self, profile: DirectoryProfile) -> None: ...
    def next_profile_ref(self, tenant_id: str) -> str: ...


class ISamlProviderRepository(Protocol):
    async def save(self, provider: SamlProvider) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[SamlProvider]: ...
    async def find_by_ref(self, tenant_id: str, provider_ref: str) -> SamlProvider | None: ...
    def next_provider_ref(self, tenant_id: str) -> str: ...


class ILdapConnectorRepository(Protocol):
    async def save(self, connector: LdapConnector) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[LdapConnector]: ...
    async def find_by_ref(self, tenant_id: str, connector_ref: str) -> LdapConnector | None: ...
    def next_connector_ref(self, tenant_id: str) -> str: ...


class IScimProviderRepository(Protocol):
    async def save(self, provider: ScimProvider) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[ScimProvider]: ...
    async def find_by_ref(self, tenant_id: str, provider_ref: str) -> ScimProvider | None: ...
    async def find_by_token(self, tenant_id: str, bearer_token: str) -> ScimProvider | None: ...
    def next_provider_ref(self, tenant_id: str) -> str: ...


class ISamlRelayStateStore(Protocol):
    async def put(self, relay_state: str, payload: dict, ttl_seconds: int) -> None: ...
    async def pop(self, relay_state: str) -> dict | None: ...


class IDirectorySyncJobRepository(Protocol):
    async def save(self, job: DirectorySyncJob) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[DirectorySyncJob]: ...
    async def list_pending(self, tenant_id: str) -> list[DirectorySyncJob]: ...
    async def find_by_ref(self, tenant_id: str, job_ref: str) -> DirectorySyncJob | None: ...
    def next_job_ref(self, tenant_id: str) -> str: ...


class IIdentityProvisioningPort(Protocol):
    async def provision_user(
        self,
        *,
        tenant_id: str,
        email: str,
        display_name: str,
        external_id: str,
        correlation_id: str,
    ) -> dict: ...

    async def find_user_id_by_email(self, tenant_id: str, email: str) -> str | None: ...

    async def issue_tokens_for_user(
        self,
        *,
        tenant_id: str,
        user_id: str,
        correlation_id: str,
        ip_address: str | None = None,
        user_agent: str | None = None,
    ) -> dict: ...


class ILdapDirectoryClient(Protocol):
    async def search_users(self, connector: LdapConnector) -> list[dict]: ...
