"""Enterprise Bank Reconciliation repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.treasury.domain.aggregates.bank_reconciliation_engine import (
    BankStatementImport,
    EnterpriseBankReconciliation,
    ReconciliationAuditEntry,
)


class IBankStatementImportRepository(Protocol):
    async def save(self, statement: BankStatementImport) -> None: ...
    async def find_by_id(self, statement_id: str) -> BankStatementImport | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[BankStatementImport]: ...


class IEnterpriseBankReconciliationRepository(Protocol):
    async def save(self, reconciliation: EnterpriseBankReconciliation) -> None: ...
    async def find_by_id(self, reconciliation_id: str) -> EnterpriseBankReconciliation | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[EnterpriseBankReconciliation]: ...


class IReconciliationAuditRepository(Protocol):
    async def save(self, entry: ReconciliationAuditEntry) -> None: ...
    async def list_by_reconciliation(self, reconciliation_id: str) -> list[ReconciliationAuditEntry]: ...
    async def list_by_tenant(self, tenant_id: str) -> list[ReconciliationAuditEntry]: ...
