"""Bank Account Management repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.treasury.domain.aggregates.bank_account import (
    AuthorizedSignatory,
    Bank,
    BankAccount,
    BankAccountDocument,
    BankBranch,
)


class IBankRepository(Protocol):
    async def save(self, bank: Bank) -> None: ...
    async def find_by_id(self, bank_id: str) -> Bank | None: ...
    async def find_by_code(self, tenant_id: str, code: str) -> Bank | None: ...
    async def list_by_tenant(self, tenant_id: str, organization_id: str | None = None) -> list[Bank]: ...


class IBankBranchRepository(Protocol):
    async def save(self, branch: BankBranch) -> None: ...
    async def find_by_id(self, branch_id: str) -> BankBranch | None: ...
    async def find_by_code(self, tenant_id: str, bank_id: str, code: str) -> BankBranch | None: ...
    async def list_by_bank(self, tenant_id: str, bank_id: str) -> list[BankBranch]: ...
    async def list_by_tenant(self, tenant_id: str, organization_id: str | None = None) -> list[BankBranch]: ...


class IBankAccountRepository(Protocol):
    async def save(self, account: BankAccount) -> None: ...
    async def find_by_id(self, account_id: str) -> BankAccount | None: ...
    async def find_by_code(self, tenant_id: str, code: str) -> BankAccount | None: ...
    async def list_by_tenant(
        self, tenant_id: str, organization_id: str | None = None
    ) -> list[BankAccount]: ...
    async def list_by_bank(self, tenant_id: str, bank_id: str) -> list[BankAccount]: ...


class ISignatoryRepository(Protocol):
    async def save(self, signatory: AuthorizedSignatory) -> None: ...
    async def find_by_id(self, signatory_id: str) -> AuthorizedSignatory | None: ...
    async def list_by_account(self, bank_account_id: str) -> list[AuthorizedSignatory]: ...


class IBankAccountDocumentRepository(Protocol):
    async def save(self, document: BankAccountDocument) -> None: ...
    async def find_by_id(self, document_id: str) -> BankAccountDocument | None: ...
    async def list_by_account(self, bank_account_id: str) -> list[BankAccountDocument]: ...
