"""Cash Management repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.treasury.domain.aggregates.cash_management import (
    CashClosing,
    CashCount,
    CashLocation,
    CashReconciliation,
    CashTransaction,
    CashVerification,
)


class ICashLocationRepository(Protocol):
    async def save(self, location: CashLocation) -> None: ...
    async def find_by_id(self, location_id: str) -> CashLocation | None: ...
    async def find_by_code(self, tenant_id: str, code: str) -> CashLocation | None: ...
    async def list_by_tenant(
        self, tenant_id: str, organization_id: str | None = None
    ) -> list[CashLocation]: ...


class ICashTransactionRepository(Protocol):
    async def save(self, transaction: CashTransaction) -> None: ...
    async def find_by_id(self, transaction_id: str) -> CashTransaction | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[CashTransaction]: ...
    async def list_by_location(self, location_id: str) -> list[CashTransaction]: ...


class ICashCountRepository(Protocol):
    async def save(self, count: CashCount) -> None: ...
    async def find_by_id(self, count_id: str) -> CashCount | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[CashCount]: ...
    async def list_by_location(self, location_id: str) -> list[CashCount]: ...


class ICashVerificationRepository(Protocol):
    async def save(self, verification: CashVerification) -> None: ...
    async def list_by_count(self, cash_count_id: str) -> list[CashVerification]: ...


class ICashClosingRepository(Protocol):
    async def save(self, closing: CashClosing) -> None: ...
    async def find_by_id(self, closing_id: str) -> CashClosing | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[CashClosing]: ...
    async def list_open_by_location(self, location_id: str) -> list[CashClosing]: ...


class ICashReconciliationRepository(Protocol):
    async def save(self, reconciliation: CashReconciliation) -> None: ...
    async def find_by_id(self, reconciliation_id: str) -> CashReconciliation | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[CashReconciliation]: ...
