"""Treasury repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.treasury.domain.aggregates.bank_reconciliation import BankReconciliation
from contexts.treasury.domain.aggregates.cash_forecast import CashForecast
from contexts.treasury.domain.aggregates.treasury_account import TreasuryAccount
from contexts.treasury.domain.aggregates.treasury_transfer import TreasuryTransfer


class ITreasuryAccountRepository(Protocol):
    async def save(self, account: TreasuryAccount) -> None: ...
    async def find_by_id(self, account_id: str) -> TreasuryAccount | None: ...
    async def find_by_code(self, tenant_id: str, code: str) -> TreasuryAccount | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[TreasuryAccount]: ...


class ITreasuryTransferRepository(Protocol):
    async def save(self, transfer: TreasuryTransfer) -> None: ...
    async def find_by_id(self, transfer_id: str) -> TreasuryTransfer | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[TreasuryTransfer]: ...


class IBankReconciliationRepository(Protocol):
    async def save(self, reconciliation: BankReconciliation) -> None: ...
    async def find_by_id(self, reconciliation_id: str) -> BankReconciliation | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[BankReconciliation]: ...


class ICashForecastRepository(Protocol):
    async def save(self, forecast: CashForecast) -> None: ...
    async def find_by_id(self, forecast_id: str) -> CashForecast | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[CashForecast]: ...
