"""Identity risk repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.identity_risk.domain.aggregates.identity_risk_platform import (
    AnomalyAlert,
    RiskProfile,
    RiskScore,
    RiskSignal,
)


class IRiskProfileRepository(Protocol):
    async def find_by_tenant(self, tenant_id: str) -> RiskProfile | None: ...
    async def save(self, profile: RiskProfile) -> None: ...
    def next_profile_ref(self, tenant_id: str) -> str: ...


class IRiskSignalRepository(Protocol):
    async def save(self, signal: RiskSignal) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[RiskSignal]: ...
    def next_signal_ref(self, tenant_id: str) -> str: ...


class IRiskScoreRepository(Protocol):
    async def save(self, score: RiskScore) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[RiskScore]: ...
    async def find_by_ref(self, tenant_id: str, score_ref: str) -> RiskScore | None: ...
    def next_score_ref(self, tenant_id: str) -> str: ...


class IAnomalyAlertRepository(Protocol):
    async def save(self, alert: AnomalyAlert) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[AnomalyAlert]: ...
    def next_alert_ref(self, tenant_id: str) -> str: ...
