"""Security ports — implemented in infrastructure/security/."""
from __future__ import annotations

from typing import Any, Protocol


class IPasswordHasher(Protocol):
    async def hash(self, plain: str) -> str: ...

    async def verify(self, plain: str, hashed: str) -> bool: ...


class ITokenService(Protocol):
    def sign_access(self, payload: dict[str, Any]) -> str: ...

    def sign_refresh(self, payload: dict[str, Any]) -> str: ...

    def verify_access(self, token: str) -> dict[str, Any]: ...

    def verify_refresh(self, token: str) -> dict[str, Any]: ...

    def hash_refresh_token(self, token: str) -> str: ...


class IMfaService(Protocol):
    def generate_secret(self) -> str: ...

    def provisioning_uri(self, email: str, secret: str, issuer: str = "Marpich ERP") -> str: ...

    def verify(self, secret: str, code: str) -> bool: ...

    def generate_backup_codes(self, count: int = 8) -> list[str]: ...
