"""Authentication repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.authentication.domain.aggregates.authentication_platform import (
    AuthenticationProfile,
    OidcProvider,
    WebAuthnCredential,
)


class IAuthenticationProfileRepository(Protocol):
    async def find_by_tenant(self, tenant_id: str) -> AuthenticationProfile | None: ...
    async def save(self, profile: AuthenticationProfile) -> None: ...
    def next_profile_ref(self, tenant_id: str) -> str: ...


class IWebAuthnCredentialRepository(Protocol):
    async def save(self, credential: WebAuthnCredential) -> None: ...
    async def list_by_user(self, tenant_id: str, user_id: str) -> list[WebAuthnCredential]: ...
    async def list_by_tenant(self, tenant_id: str) -> list[WebAuthnCredential]: ...
    async def find_by_credential_id(self, tenant_id: str, credential_id: str) -> WebAuthnCredential | None: ...
    async def find_by_ref(self, tenant_id: str, credential_ref: str) -> WebAuthnCredential | None: ...
    async def delete(self, tenant_id: str, credential_ref: str) -> bool: ...
    def next_credential_ref(self, tenant_id: str) -> str: ...


class IOidcProviderRepository(Protocol):
    async def save(self, provider: OidcProvider) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[OidcProvider]: ...
    async def find_by_ref(self, tenant_id: str, provider_ref: str) -> OidcProvider | None: ...
    def next_provider_ref(self, tenant_id: str) -> str: ...


class IWebAuthnChallengeStore(Protocol):
    async def put_registration(self, challenge_id: str, payload: dict, ttl_seconds: int) -> None: ...
    async def pop_registration(self, challenge_id: str) -> dict | None: ...
    async def put_authentication(self, challenge_id: str, payload: dict, ttl_seconds: int) -> None: ...
    async def pop_authentication(self, challenge_id: str) -> dict | None: ...


class IOidcStateStore(Protocol):
    async def put(self, state: str, payload: dict, ttl_seconds: int) -> None: ...
    async def pop(self, state: str) -> dict | None: ...


class IIdentityTokenPort(Protocol):
    async def issue_tokens_for_user(
        self,
        *,
        tenant_id: str,
        user_id: str,
        correlation_id: str,
        ip_address: str | None = None,
        user_agent: str | None = None,
    ) -> dict: ...

    async def find_user_id_by_email(self, tenant_id: str, email: str) -> str | None: ...
