"""Identity resilience repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.identity_resilience.domain.aggregates.identity_resilience_platform import (
    FailoverEvent,
    RegionDescriptor,
    ResilienceProfile,
    WorkerDeployment,
)


class IResilienceProfileRepository(Protocol):
    async def find_by_tenant(self, tenant_id: str) -> ResilienceProfile | None: ...
    async def save(self, profile: ResilienceProfile) -> None: ...
    def next_profile_ref(self, tenant_id: str) -> str: ...


class IRegionRepository(Protocol):
    async def save(self, region: RegionDescriptor) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[RegionDescriptor]: ...
    async def find_by_region_id(self, tenant_id: str, region_id: str) -> RegionDescriptor | None: ...
    def next_region_ref(self, tenant_id: str) -> str: ...


class IWorkerDeploymentRepository(Protocol):
    async def save(self, worker: WorkerDeployment) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[WorkerDeployment]: ...
    async def find_by_ref(self, tenant_id: str, worker_ref: str) -> WorkerDeployment | None: ...
    async def find_leader(self, tenant_id: str, worker_type: str) -> WorkerDeployment | None: ...
    def next_worker_ref(self, tenant_id: str) -> str: ...


class IFailoverEventRepository(Protocol):
    async def save(self, event: FailoverEvent) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[FailoverEvent]: ...
    def next_failover_ref(self, tenant_id: str) -> str: ...


class IDirectoryWorkerPort(Protocol):
    async def run_sync_worker(self, tenant_id: str) -> dict: ...


class IRiskWorkerPort(Protocol):
    async def process_pending_scores(self, tenant_id: str) -> dict: ...
