"""Runtime ports for Identity Federation — no infrastructure imports in application."""
from __future__ import annotations

from typing import Any, Protocol


class IOAuth2AuthorizationServer(Protocol):
    def register_client(self, **kwargs: Any) -> dict: ...

    def authorize(self, **kwargs: Any) -> dict: ...

    def token(self, **kwargs: Any) -> dict: ...

    def introspect(self, **kwargs: Any) -> dict: ...

    def revoke(self, **kwargs: Any) -> dict: ...


class IOidcProvider(Protocol):
    def discovery(self, **kwargs: Any) -> dict: ...

    def jwks(self, **kwargs: Any) -> dict: ...

    def authorize(self, **kwargs: Any) -> dict: ...

    def token(self, **kwargs: Any) -> dict: ...

    def userinfo(self, **kwargs: Any) -> dict: ...


class IScimServer(Protocol):
    def create_user(self, **kwargs: Any) -> dict: ...

    def get_user(self, **kwargs: Any) -> dict: ...

    def list_users(self, **kwargs: Any) -> dict: ...

    def patch_user(self, **kwargs: Any) -> dict: ...

    def delete_user(self, **kwargs: Any) -> dict: ...


class ICertificateManager(Protocol):
    def issue(self, **kwargs: Any) -> dict: ...

    def rotate(self, **kwargs: Any) -> dict: ...

    def list_active(self, **kwargs: Any) -> list: ...


class IProtocolBridge(Protocol):
    async def exchange(self, **kwargs: Any) -> dict: ...

    async def provision_link(self, **kwargs: Any) -> dict: ...


class IFederationMetrics(Protocol):
    def increment(self, metric: str, value: float = 1.0) -> None: ...

    def record_latency(self, metric: str, ms: float) -> None: ...

    def snapshot(self) -> dict: ...


class IFederationAuditTrail(Protocol):
    def append(self, **kwargs: Any) -> dict: ...

    def list_by_tenant(self, tenant_id: str, *, limit: int = 50) -> list[dict]: ...


class IAdaptiveAuthFederationPort(Protocol):
    async def evaluate_zero_trust(self, **kwargs: Any) -> dict: ...

    async def evaluate_risk(self, **kwargs: Any) -> dict: ...


class IIdentityRiskFederationPort(Protocol):
    async def score_federation(self, **kwargs: Any) -> dict: ...
