"""Data isolation repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.data_isolation.domain.aggregates.data_isolation_platform import IsolationProfile, Principal


class IIsolationProfileRepository(Protocol):
    async def find_by_tenant(self, tenant_id: str) -> IsolationProfile | None: ...
    async def save(self, profile: IsolationProfile) -> None: ...
    def next_profile_ref(self, tenant_id: str) -> str: ...


class IPrincipalRepository(Protocol):
    async def save(self, principal: Principal) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[Principal]: ...
    async def find_by_ref(self, tenant_id: str, principal_ref: str) -> Principal | None: ...
    async def find_by_user_id(self, tenant_id: str, user_id: str) -> Principal | None: ...
    def next_principal_ref(self, tenant_id: str) -> str: ...


class IIdentityPrincipalSource(Protocol):
    async def list_users(self, tenant_id: str) -> list[dict]: ...
