"""Permission Registry repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.permission_registry.domain.aggregates.permission_registry_platform import (
    Permission,
    PermissionSet,
    RegistryProfile,
    RegistryRole,
    RoleBinding,
)


class IRegistryProfileRepository(Protocol):
    async def save(self, profile: RegistryProfile) -> None: ...
    async def find_by_tenant(self, tenant_id: str) -> RegistryProfile | None: ...
    def next_profile_ref(self, tenant_id: str) -> str: ...


class IPermissionRepository(Protocol):
    async def save(self, permission: Permission) -> None: ...
    async def find_by_code(self, code: str) -> Permission | None: ...
    async def list_all(self, *, module: str | None = None) -> list[Permission]: ...


class IRegistryRoleRepository(Protocol):
    async def save(self, role: RegistryRole) -> None: ...
    async def find_by_ref(self, tenant_id: str, role_ref: str) -> RegistryRole | None: ...
    async def find_by_code(self, tenant_id: str, code: str) -> RegistryRole | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[RegistryRole]: ...
    def next_role_ref(self, tenant_id: str) -> str: ...


class IRoleBindingRepository(Protocol):
    async def save(self, binding: RoleBinding) -> None: ...
    async def find_by_ref(self, tenant_id: str, binding_ref: str) -> RoleBinding | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[RoleBinding]: ...
    async def list_by_principal(self, tenant_id: str, principal_id: str) -> list[RoleBinding]: ...
    async def delete(self, tenant_id: str, binding_ref: str) -> bool: ...
    def next_binding_ref(self, tenant_id: str) -> str: ...


class IPermissionSetRepository(Protocol):
    async def save(self, permission_set: PermissionSet) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[PermissionSet]: ...
    def next_set_ref(self, tenant_id: str) -> str: ...


class IIdentityRegistryPort(Protocol):
    async def sync_role(
        self,
        tenant_id: str,
        *,
        role_id: str,
        code: str,
        name: str,
        permission_codes: list[str],
        is_system: bool,
    ) -> None: ...

    async def assign_role_to_principal(self, tenant_id: str, principal_id: str, role_id: str) -> None: ...
    async def revoke_role_from_principal(self, tenant_id: str, principal_id: str, role_id: str) -> None: ...
    async def principal_exists(self, tenant_id: str, principal_id: str) -> bool: ...
