"""Authorization repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.authorization.domain.aggregates.authorization_platform import (
    AbacPolicy,
    AccessDecision,
    AuthorizationProfile,
)


class IAuthorizationProfileRepository(Protocol):
    async def save(self, profile: AuthorizationProfile) -> None: ...
    async def find_by_tenant(self, tenant_id: str) -> AuthorizationProfile | None: ...
    def next_profile_ref(self, tenant_id: str) -> str: ...


class IAbacPolicyRepository(Protocol):
    async def save(self, policy: AbacPolicy) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[AbacPolicy]: ...
    def next_policy_ref(self, tenant_id: str) -> str: ...


class IAccessDecisionRepository(Protocol):
    async def save(self, decision: AccessDecision) -> None: ...
    async def list_by_tenant(self, tenant_id: str, *, limit: int = 50) -> list[AccessDecision]: ...
    def next_decision_ref(self, tenant_id: str) -> str: ...


class IPrincipalAccessPort(Protocol):
    async def resolve_permissions(self, tenant_id: str, principal_id: str) -> list[str]: ...
    async def resolve_principal_attributes(self, tenant_id: str, principal_id: str) -> dict: ...
