"""Bounded context registry — single source of truth."""
CONTEXTS = {
    "core_platform": 'Core Platform',
    "identity": 'Identity',
    "finance": 'Finance',
    "accounting": 'Accounting',
    "banking": 'Banking',
    "islamic_banking": 'Islamic Banking',
    "treasury": 'Treasury',
    "currency_exchange": 'Currency Exchange',
    "tax": 'Tax',
    "payroll": 'Payroll',
    "human_resources": 'Human Resources',
    "crm": 'CRM',
    "sales": 'Sales',
    "procurement": 'Procurement',
    "inventory": 'Inventory',
    "warehouse": 'Warehouse',
    "manufacturing": 'Manufacturing',
    "construction": 'Construction',
    "projects": 'Projects',
    "university": 'University',
    "school": 'School',
    "hospital": 'Hospital',
    "laboratory": 'Laboratory',
    "pharmacy": 'Pharmacy',
    "hotel": 'Hotel',
    "restaurant": 'Restaurant',
    "real_estate": 'Real Estate',
    "government": 'Government',
    "ngo": 'NGO',
    "workflow": 'Workflow',
    "documents": 'Documents',
    "analytics": 'Analytics',
    "ai": 'AI',
    "notifications": 'Notifications',
    "media": 'Media',
    "search": 'Search',
    "settings": 'Settings',
}

CONTEXT_TYPES = {
    "core_platform": "platform",
    "identity": "platform",
    "finance": "generic",
    "accounting": "generic",
    "banking": "specialized",
    "islamic_banking": "specialized",
    "treasury": "generic",
    "currency_exchange": "specialized",
    "tax": "generic",
    "payroll": "generic",
    "human_resources": "generic",
    "crm": "generic",
    "sales": "generic",
    "procurement": "generic",
    "inventory": "generic",
    "warehouse": "generic",
    "manufacturing": "generic",
    "construction": "industry",
    "projects": "generic",
    "university": "industry",
    "school": "industry",
    "hospital": "industry",
    "laboratory": "industry",
    "pharmacy": "industry",
    "hotel": "industry",
    "restaurant": "industry",
    "real_estate": "industry",
    "government": "industry",
    "ngo": "industry",
    "workflow": "platform",
    "documents": "platform",
    "analytics": "platform",
    "ai": "platform",
    "notifications": "platform",
    "media": "platform",
    "search": "platform",
    "settings": "platform",
}
