"""Account hierarchy repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.financial_kernel.domain.aggregates.account_hierarchy import (
    AccountTree,
    AccountTreeVersion,
)


class IAccountTreeRepository(Protocol):
    async def save(self, tree: AccountTree) -> None: ...
    async def find_by_id(self, tree_id: str) -> AccountTree | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[AccountTree]: ...
    async def find_default(self, tenant_id: str) -> AccountTree | None: ...


class IAccountTreeVersionRepository(Protocol):
    async def save(self, version: AccountTreeVersion) -> None: ...
    async def find_by_id(self, version_id: str) -> AccountTreeVersion | None: ...
    async def list_by_tree(self, tree_id: str) -> list[AccountTreeVersion]: ...
    async def find_by_version_number(
        self, tree_id: str, version_number: int
    ) -> AccountTreeVersion | None: ...
