"""Enterprise cost center repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.financial_kernel.domain.aggregates.cost_center import (
    CenterAllocation,
    EnterpriseCostCenter,
    EnterpriseProfitCenter,
)


class IEnterpriseCostCenterRepository(Protocol):
    async def save(self, center: EnterpriseCostCenter) -> None: ...
    async def find_by_id(self, center_id: str) -> EnterpriseCostCenter | None: ...
    async def find_by_code(self, tenant_id: str, code: str) -> EnterpriseCostCenter | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[EnterpriseCostCenter]: ...
    async def list_by_type(self, tenant_id: str, center_type: str) -> list[EnterpriseCostCenter]: ...


class IEnterpriseProfitCenterRepository(Protocol):
    async def save(self, center: EnterpriseProfitCenter) -> None: ...
    async def find_by_id(self, center_id: str) -> EnterpriseProfitCenter | None: ...
    async def find_by_code(self, tenant_id: str, code: str) -> EnterpriseProfitCenter | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[EnterpriseProfitCenter]: ...


class ICenterAllocationRepository(Protocol):
    async def save(self, allocation: CenterAllocation) -> None: ...
    async def find_by_idempotency(self, tenant_id: str, key: str) -> CenterAllocation | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[CenterAllocation]: ...
    async def list_by_cost_center(self, tenant_id: str, cost_center_code: str) -> list[CenterAllocation]: ...
    async def list_by_type(self, tenant_id: str, allocation_type: str) -> list[CenterAllocation]: ...
