"""Financial workflow repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.financial_kernel.domain.aggregates.financial_workflow import FinancialWorkflow


class IFinancialWorkflowRepository(Protocol):
    async def save(self, workflow: FinancialWorkflow) -> None: ...
    async def find_by_id(self, workflow_id: str) -> FinancialWorkflow | None: ...
    async def find_by_idempotency(self, tenant_id: str, key: str) -> FinancialWorkflow | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[FinancialWorkflow]: ...
    async def list_by_type(self, tenant_id: str, workflow_type: str) -> list[FinancialWorkflow]: ...
    async def list_pending_sla_breached(self, tenant_id: str) -> list[FinancialWorkflow]: ...
