"""Financial AI repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.financial_kernel.domain.aggregates.financial_ai import (
    FinancialAIChatSession,
    FinancialAIJob,
)


class IFinancialAIJobRepository(Protocol):
    async def save(self, job: FinancialAIJob) -> None: ...
    async def find_by_id(self, job_id: str) -> FinancialAIJob | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[FinancialAIJob]: ...
    async def list_by_capability(self, tenant_id: str, capability: str) -> list[FinancialAIJob]: ...


class IFinancialAIChatRepository(Protocol):
    async def save(self, session: FinancialAIChatSession) -> None: ...
    async def find_by_id(self, session_id: str) -> FinancialAIChatSession | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[FinancialAIChatSession]: ...
