"""Financial security repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.financial_kernel.domain.aggregates.financial_security import (
    MakerCheckerRequest,
    PeriodCloseRequest,
    SecurityAuditRecord,
    SecurityPolicy,
    TransactionLock,
)


class ISecurityAuditRepository(Protocol):
    async def save(self, record: SecurityAuditRecord) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[SecurityAuditRecord]: ...
    async def list_by_resource(self, tenant_id: str, resource_type: str, resource_id: str) -> list[SecurityAuditRecord]: ...
    async def last_tamper_hash(self, tenant_id: str) -> str | None: ...


class ISecurityPolicyRepository(Protocol):
    async def save(self, policy: SecurityPolicy) -> None: ...
    async def find_by_id(self, policy_id: str) -> SecurityPolicy | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[SecurityPolicy]: ...
    async def find_for_resource(self, tenant_id: str, resource_type: str) -> list[SecurityPolicy]: ...


class IMakerCheckerRepository(Protocol):
    async def save(self, request: MakerCheckerRequest) -> None: ...
    async def find_by_id(self, request_id: str) -> MakerCheckerRequest | None: ...
    async def find_by_idempotency(self, tenant_id: str, key: str) -> MakerCheckerRequest | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[MakerCheckerRequest]: ...


class ITransactionLockRepository(Protocol):
    async def save(self, lock: TransactionLock) -> None: ...
    async def find_active(self, tenant_id: str, resource_type: str, resource_id: str) -> TransactionLock | None: ...
    async def find_by_id(self, lock_id: str) -> TransactionLock | None: ...
    async def list_active(self, tenant_id: str) -> list[TransactionLock]: ...


class IPeriodCloseRequestRepository(Protocol):
    async def save(self, request: PeriodCloseRequest) -> None: ...
    async def find_by_id(self, request_id: str) -> PeriodCloseRequest | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[PeriodCloseRequest]: ...
