"""Financial dimension repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.financial_kernel.domain.aggregates.financial_dimension import (
    DimensionAuditLog,
    DimensionValue,
)


class IDimensionValueRepository(Protocol):
    async def save(self, value: DimensionValue) -> None: ...
    async def find_by_id(self, value_id: str) -> DimensionValue | None: ...
    async def find_by_code(
        self, tenant_id: str, dimension_type: str, code: str
    ) -> DimensionValue | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[DimensionValue]: ...
    async def list_by_type(self, tenant_id: str, dimension_type: str) -> list[DimensionValue]: ...


class IDimensionAuditRepository(Protocol):
    async def save(self, entry: DimensionAuditLog) -> None: ...
    async def list_by_dimension_value(self, dimension_value_id: str) -> list[DimensionAuditLog]: ...
    async def list_by_tenant(self, tenant_id: str, *, limit: int = 100) -> list[DimensionAuditLog]: ...
