"""Financial document repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.financial_kernel.domain.aggregates.financial_document import (
    FinancialDocument,
    FinancialDocumentVersion,
)


class IFinancialDocumentRepository(Protocol):
    async def save(self, document: FinancialDocument) -> None: ...
    async def find_by_id(self, document_id: str) -> FinancialDocument | None: ...
    async def find_by_idempotency(self, tenant_id: str, key: str) -> FinancialDocument | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[FinancialDocument]: ...
    async def next_sequence(self, tenant_id: str, document_type: str) -> int: ...


class IFinancialDocumentVersionRepository(Protocol):
    async def save(self, version: FinancialDocumentVersion) -> None: ...
    async def find_by_id(self, version_id: str) -> FinancialDocumentVersion | None: ...
    async def list_by_document(self, tenant_id: str, document_id: str) -> list[FinancialDocumentVersion]: ...
    async def next_version_number(self, tenant_id: str, document_id: str) -> int: ...
