"""Fiscal calendar repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.financial_kernel.domain.aggregates.fiscal_calendar import (
    FiscalCalendar,
    FiscalCalendarAuditLog,
    FiscalCloseRequest,
)


class IFiscalCalendarRepository(Protocol):
    async def save(self, calendar: FiscalCalendar) -> None: ...
    async def find_by_id(self, calendar_id: str) -> FiscalCalendar | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[FiscalCalendar]: ...
    async def find_default(self, tenant_id: str, organization_id: str | None = None) -> FiscalCalendar | None: ...


class IFiscalCalendarAuditRepository(Protocol):
    async def save(self, entry: FiscalCalendarAuditLog) -> None: ...
    async def list_by_tenant(self, tenant_id: str, *, limit: int = 100) -> list[FiscalCalendarAuditLog]: ...


class IFiscalCloseRequestRepository(Protocol):
    async def save(self, request: FiscalCloseRequest) -> None: ...
    async def find_by_id(self, request_id: str) -> FiscalCloseRequest | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[FiscalCloseRequest]: ...
