"""Payment repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.financial_kernel.domain.aggregates.payment import InstallmentPlan, Payment
from contexts.financial_kernel.domain.aggregates.payment_reconciliation import PaymentReconciliation


class IPaymentRepository(Protocol):
    async def save(self, payment: Payment) -> None: ...
    async def find_by_id(self, payment_id: str) -> Payment | None: ...
    async def find_by_idempotency(self, tenant_id: str, key: str) -> Payment | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[Payment]: ...
    async def list_children(self, parent_payment_id: str) -> list[Payment]: ...


class IInstallmentPlanRepository(Protocol):
    async def save(self, plan: InstallmentPlan) -> None: ...
    async def find_by_id(self, plan_id: str) -> InstallmentPlan | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[InstallmentPlan]: ...


class IPaymentReconciliationRepository(Protocol):
    async def save(self, record: PaymentReconciliation) -> None: ...
    async def find_by_id(self, record_id: str) -> PaymentReconciliation | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[PaymentReconciliation]: ...
