"""Reconciliation repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.financial_kernel.domain.aggregates.reconciliation import (
    ReconciliationAuditLog,
    ReconciliationRun,
)


class IReconciliationRunRepository(Protocol):
    async def save(self, run: ReconciliationRun) -> None: ...
    async def find_by_id(self, run_id: str) -> ReconciliationRun | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[ReconciliationRun]: ...
    async def list_by_type(self, tenant_id: str, reconciliation_type: str) -> list[ReconciliationRun]: ...


class IReconciliationAuditRepository(Protocol):
    async def save(self, entry: ReconciliationAuditLog) -> None: ...
    async def list_by_reconciliation(self, reconciliation_id: str) -> list[ReconciliationAuditLog]: ...
    async def list_by_tenant(self, tenant_id: str, *, limit: int = 100) -> list[ReconciliationAuditLog]: ...
