"""Financial Kernel repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.financial_kernel.domain.aggregates.budget import Budget, RecurringJournal
from contexts.financial_kernel.domain.aggregates.chart_of_account import ChartOfAccount
from contexts.financial_kernel.domain.aggregates.currency import (
    CurrencyRevaluation,
    ExchangeRate,
    ExchangeRateSnapshot,
    TenantCurrencySettings,
)
from contexts.financial_kernel.domain.aggregates.dimensions import CostCenter, ProfitCenter
from contexts.financial_kernel.domain.aggregates.fiscal_period import FiscalPeriod, FiscalYear
from contexts.financial_kernel.domain.aggregates.journal import Journal


class IChartOfAccountRepository(Protocol):
    async def save(self, account: ChartOfAccount) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[ChartOfAccount]: ...
    async def find_by_id(self, account_id: str) -> ChartOfAccount | None: ...
    async def find_by_code(self, tenant_id: str, code: str) -> ChartOfAccount | None: ...
    async def find_by_key(self, tenant_id: str, account_key: str) -> ChartOfAccount | None: ...
    async def list_children(self, tenant_id: str, parent_account_id: str) -> list[ChartOfAccount]: ...


class IJournalRepository(Protocol):
    async def save(self, journal: Journal) -> None: ...
    async def find_by_id(self, journal_id: str) -> Journal | None: ...
    async def find_by_idempotency(self, tenant_id: str, key: str) -> Journal | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[Journal]: ...


class IFiscalYearRepository(Protocol):
    async def save(self, year: FiscalYear) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[FiscalYear]: ...
    async def find_by_id(self, year_id: str) -> FiscalYear | None: ...


class IFiscalPeriodRepository(Protocol):
    async def save(self, period: FiscalPeriod) -> None: ...
    async def find_open(self, tenant_id: str, organization_id: str | None = None) -> FiscalPeriod | None: ...
    async def find_by_id(self, period_id: str) -> FiscalPeriod | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[FiscalPeriod]: ...


class IDimensionRepository(Protocol):
    async def save_cost_center(self, center: CostCenter) -> None: ...
    async def save_profit_center(self, center: ProfitCenter) -> None: ...
    async def list_cost_centers(self, tenant_id: str) -> list[CostCenter]: ...
    async def list_profit_centers(self, tenant_id: str) -> list[ProfitCenter]: ...


class IBudgetRepository(Protocol):
    async def save(self, budget: Budget) -> None: ...
    async def find_match(
        self, tenant_id: str, period_id: str, account_code: str, cost_center: str | None
    ) -> Budget | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[Budget]: ...


class IRecurringJournalRepository(Protocol):
    async def save(self, template: RecurringJournal) -> None: ...
    async def find_by_id(self, template_id: str) -> RecurringJournal | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[RecurringJournal]: ...


class ICurrencySettingsRepository(Protocol):
    async def save(self, settings: TenantCurrencySettings) -> None: ...
    async def find_by_tenant(self, tenant_id: str) -> TenantCurrencySettings | None: ...


class IExchangeRateRepository(Protocol):
    async def save(self, rate: ExchangeRate) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[ExchangeRate]: ...
    async def list_history(
        self,
        tenant_id: str,
        *,
        from_currency: str | None = None,
        to_currency: str | None = None,
        rate_type: str | None = None,
    ) -> list[ExchangeRate]: ...


class IExchangeRateSnapshotRepository(Protocol):
    async def save(self, snapshot: ExchangeRateSnapshot) -> None: ...
    async def find_by_id(self, snapshot_id: str) -> ExchangeRateSnapshot | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[ExchangeRateSnapshot]: ...
    async def find_by_journal(self, journal_id: str) -> ExchangeRateSnapshot | None: ...


class ICurrencyRevaluationRepository(Protocol):
    async def save(self, revaluation: CurrencyRevaluation) -> None: ...
    async def find_by_id(self, revaluation_id: str) -> CurrencyRevaluation | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[CurrencyRevaluation]: ...
