"""Subledger repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.financial_kernel.domain.aggregates.subledger import (
    Subledger,
    SubledgerEntry,
    SubledgerReconciliation,
)


class ISubledgerRepository(Protocol):
    async def save(self, subledger: Subledger) -> None: ...
    async def find_by_id(self, subledger_id: str) -> Subledger | None: ...
    async def find_by_type(self, tenant_id: str, subledger_type: str) -> Subledger | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[Subledger]: ...


class ISubledgerEntryRepository(Protocol):
    async def save(self, entry: SubledgerEntry) -> None: ...
    async def find_by_id(self, entry_id: str) -> SubledgerEntry | None: ...
    async def find_by_idempotency(self, tenant_id: str, key: str) -> SubledgerEntry | None: ...
    async def list_by_subledger(self, subledger_id: str) -> list[SubledgerEntry]: ...
    async def list_by_tenant(self, tenant_id: str) -> list[SubledgerEntry]: ...


class ISubledgerReconciliationRepository(Protocol):
    async def save(self, reconciliation: SubledgerReconciliation) -> None: ...
    async def find_by_id(self, reconciliation_id: str) -> SubledgerReconciliation | None: ...
    async def list_by_subledger(self, subledger_id: str) -> list[SubledgerReconciliation]: ...
    async def list_by_tenant(self, tenant_id: str) -> list[SubledgerReconciliation]: ...
