from __future__ import annotations
from abc import ABC, abstractmethod
from contexts.identity_digital_twin.domain.aggregates.identity_digital_twin_platform import DigitalTwin, TwinSnapshot, TwinSimulation, TwinDriftAlert
class ITwinRepository(ABC):
    @abstractmethod
    async def save(self, twin: DigitalTwin) -> None: ...
    @abstractmethod
    async def find_by_ref(self, tenant_id: str, twin_ref: str) -> DigitalTwin | None: ...
    @abstractmethod
    async def list_by_tenant(self, tenant_id: str, *, limit: int = 100) -> list[DigitalTwin]: ...
    @abstractmethod
    def next_ref(self, tenant_id: str) -> str: ...
class ISnapshotRepository(ABC):
    @abstractmethod
    async def save(self, snapshot: TwinSnapshot) -> None: ...
    @abstractmethod
    async def list_by_twin(self, tenant_id: str, twin_ref: str, *, limit: int = 50) -> list[TwinSnapshot]: ...
    @abstractmethod
    def next_ref(self, tenant_id: str) -> str: ...
class ISimulationRepository(ABC):
    @abstractmethod
    async def save(self, simulation: TwinSimulation) -> None: ...
    @abstractmethod
    async def list_by_twin(self, tenant_id: str, twin_ref: str, *, limit: int = 50) -> list[TwinSimulation]: ...
    @abstractmethod
    def next_ref(self, tenant_id: str) -> str: ...
class IDriftAlertRepository(ABC):
    @abstractmethod
    async def save(self, alert: TwinDriftAlert) -> None: ...
    @abstractmethod
    async def list_by_tenant(self, tenant_id: str, *, limit: int = 100) -> list[TwinDriftAlert]: ...
    @abstractmethod
    def next_ref(self, tenant_id: str) -> str: ...
