"""Banking Security Platform repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.banking.domain.aggregates.banking_security_engine import (
    EmergencyFreeze,
    LimitUsageTracker,
    SecurityApprovalRequest,
    SecurityAuditEntry,
    SecurityDevice,
    SecuritySession,
    TransactionMonitorAlert,
)


class ISecurityApprovalRepository(Protocol):
    async def save(self, request: SecurityApprovalRequest) -> None: ...
    async def find_by_id(self, request_id: str) -> SecurityApprovalRequest | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[SecurityApprovalRequest]: ...
    def next_request_ref(self, tenant_id: str) -> str: ...


class ISecurityDeviceRepository(Protocol):
    async def save(self, device: SecurityDevice) -> None: ...
    async def find_by_fingerprint(self, tenant_id: str, user_id: str, fingerprint: str) -> SecurityDevice | None: ...
    async def list_by_user(self, tenant_id: str, user_id: str) -> list[SecurityDevice]: ...
    def next_device_ref(self, tenant_id: str) -> str: ...


class ISecuritySessionRepository(Protocol):
    async def save(self, session: SecuritySession) -> None: ...
    async def find_by_id(self, session_id: str) -> SecuritySession | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[SecuritySession]: ...
    def next_session_ref(self, tenant_id: str) -> str: ...


class ITransactionMonitorRepository(Protocol):
    async def save(self, alert: TransactionMonitorAlert) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[TransactionMonitorAlert]: ...
    def next_alert_ref(self, tenant_id: str) -> str: ...


class IEmergencyFreezeRepository(Protocol):
    async def save(self, freeze: EmergencyFreeze) -> None: ...
    async def find_active(self, tenant_id: str) -> EmergencyFreeze | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[EmergencyFreeze]: ...
    def next_freeze_ref(self, tenant_id: str) -> str: ...


class ISecurityAuditRepository(Protocol):
    async def save(self, entry: SecurityAuditEntry) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[SecurityAuditEntry]: ...
    async def last_tamper_hash(self, tenant_id: str) -> str | None: ...
    def next_audit_ref(self, tenant_id: str) -> str: ...


class ILimitUsageRepository(Protocol):
    async def save(self, tracker: LimitUsageTracker) -> None: ...
    async def get_for_user(self, tenant_id: str, user_id: str, usage_date: str) -> LimitUsageTracker | None: ...
