"""Branch Banking Platform repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.banking.domain.aggregates.branch_banking_engine import (
    BranchAuditEntry,
    BranchCashLimit,
    BranchDaySession,
    BranchEmployeeAssignment,
    BranchExtension,
    BranchKPIRecord,
    BranchOffice,
    BranchVault,
    BranchVaultMovement,
)


class IBranchOfficeRepository(Protocol):
    async def save(self, office: BranchOffice) -> None: ...
    async def find_by_id(self, office_id: str) -> BranchOffice | None: ...
    async def find_by_code(self, tenant_id: str, code: str) -> BranchOffice | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[BranchOffice]: ...
    def next_office_ref(self, tenant_id: str) -> str: ...


class IBranchExtensionRepository(Protocol):
    async def save(self, extension: BranchExtension) -> None: ...
    async def list_by_office(self, office_id: str) -> list[BranchExtension]: ...
    async def list_by_tenant(self, tenant_id: str) -> list[BranchExtension]: ...
    def next_extension_ref(self, tenant_id: str) -> str: ...


class IBranchDaySessionRepository(Protocol):
    async def save(self, session: BranchDaySession) -> None: ...
    async def list_by_office(self, office_id: str) -> list[BranchDaySession]: ...
    async def list_by_tenant(self, tenant_id: str) -> list[BranchDaySession]: ...
    def next_session_ref(self, tenant_id: str) -> str: ...


class IBranchVaultRepository(Protocol):
    async def save(self, vault: BranchVault) -> None: ...
    async def find_by_office(self, office_id: str) -> BranchVault | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[BranchVault]: ...
    def next_vault_ref(self, tenant_id: str) -> str: ...


class IBranchVaultMovementRepository(Protocol):
    async def save(self, movement: BranchVaultMovement) -> None: ...
    async def list_by_vault(self, vault_id: str) -> list[BranchVaultMovement]: ...
    def next_movement_ref(self, tenant_id: str) -> str: ...


class IBranchCashLimitRepository(Protocol):
    async def save(self, limit: BranchCashLimit) -> None: ...
    async def list_by_office(self, office_id: str) -> list[BranchCashLimit]: ...
    async def list_by_tenant(self, tenant_id: str) -> list[BranchCashLimit]: ...
    def next_limit_ref(self, tenant_id: str) -> str: ...


class IBranchEmployeeAssignmentRepository(Protocol):
    async def save(self, assignment: BranchEmployeeAssignment) -> None: ...
    async def list_by_office(self, office_id: str) -> list[BranchEmployeeAssignment]: ...
    async def list_by_tenant(self, tenant_id: str) -> list[BranchEmployeeAssignment]: ...
    def next_assignment_ref(self, tenant_id: str) -> str: ...


class IBranchKPIRepository(Protocol):
    async def save(self, kpi: BranchKPIRecord) -> None: ...
    async def list_by_office(self, office_id: str) -> list[BranchKPIRecord]: ...
    async def list_by_tenant(self, tenant_id: str) -> list[BranchKPIRecord]: ...
    def next_kpi_ref(self, tenant_id: str) -> str: ...


class IBranchAuditRepository(Protocol):
    async def save(self, entry: BranchAuditEntry) -> None: ...
    async def list_by_office(self, office_id: str) -> list[BranchAuditEntry]: ...
