"""Banking Customer and Account repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.banking.domain.aggregates.customer_account_engine import (
    BankingAccount,
    BankingAccountAudit,
    BankingAccountProduct,
    BankingCustomer,
    BankingCustomerKYC,
)


class ICustomerRepository(Protocol):
    async def save(self, customer: BankingCustomer) -> None: ...

    async def find_by_id(self, customer_id: str) -> BankingCustomer | None: ...

    async def find_by_email(self, tenant_id: str, email: str) -> BankingCustomer | None: ...

    async def list_by_tenant(self, tenant_id: str) -> list[BankingCustomer]: ...


class IKycRepository(Protocol):
    async def save(self, kyc: BankingCustomerKYC) -> None: ...

    async def find_by_id(self, kyc_id: str) -> BankingCustomerKYC | None: ...

    async def list_by_customer(self, customer_id: str) -> list[BankingCustomerKYC]: ...

    async def list_by_tenant(self, tenant_id: str) -> list[BankingCustomerKYC]: ...


class IAccountProductRepository(Protocol):
    async def save(self, product: BankingAccountProduct) -> None: ...

    async def find_by_code(self, tenant_id: str, product_code: str) -> BankingAccountProduct | None: ...

    async def list_by_tenant(self, tenant_id: str) -> list[BankingAccountProduct]: ...


class IAccountRepository(Protocol):
    async def save(self, account: BankingAccount) -> None: ...

    async def find_by_id(self, account_id: str) -> BankingAccount | None: ...

    async def find_by_number(self, tenant_id: str, account_number: str) -> BankingAccount | None: ...

    async def list_by_tenant(self, tenant_id: str) -> list[BankingAccount]: ...

    async def list_by_customer(self, customer_id: str) -> list[BankingAccount]: ...

    def next_account_number(self, tenant_id: str, prefix: str = "ACC") -> str: ...


class IAccountAuditRepository(Protocol):
    async def save(self, entry: BankingAccountAudit) -> None: ...

    async def list_by_account(self, account_id: str) -> list[BankingAccountAudit]: ...

    async def list_by_tenant(self, tenant_id: str) -> list[BankingAccountAudit]: ...
