"""Deposit Management repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.banking.domain.aggregates.deposit_management_engine import (
    DepositAuditEntry,
    DepositCertificate,
    DepositInterestAccrual,
    DepositProfile,
    DepositStatement,
    DepositTransaction,
    DepositWorkflowRequest,
    ProfitDistributionRule,
)


class IProfitRuleRepository(Protocol):
    async def save(self, rule: ProfitDistributionRule) -> None: ...

    async def find_by_code(self, tenant_id: str, rule_code: str) -> ProfitDistributionRule | None: ...

    async def list_by_tenant(self, tenant_id: str) -> list[ProfitDistributionRule]: ...


class IDepositProfileRepository(Protocol):
    async def save(self, deposit: DepositProfile) -> None: ...

    async def find_by_id(self, deposit_id: str) -> DepositProfile | None: ...

    async def find_by_account(self, account_id: str) -> DepositProfile | None: ...

    async def list_by_tenant(self, tenant_id: str) -> list[DepositProfile]: ...


class IDepositTransactionRepository(Protocol):
    async def save(self, transaction: DepositTransaction) -> None: ...

    async def find_by_id(self, transaction_id: str) -> DepositTransaction | None: ...

    async def list_by_deposit(self, deposit_id: str) -> list[DepositTransaction]: ...

    async def list_by_tenant(self, tenant_id: str) -> list[DepositTransaction]: ...

    def next_transaction_ref(self, tenant_id: str) -> str: ...


class IDepositAccrualRepository(Protocol):
    async def save(self, accrual: DepositInterestAccrual) -> None: ...

    async def list_by_deposit(self, deposit_id: str) -> list[DepositInterestAccrual]: ...

    async def list_by_tenant(self, tenant_id: str) -> list[DepositInterestAccrual]: ...

    def next_accrual_ref(self, tenant_id: str) -> str: ...


class IDepositCertificateRepository(Protocol):
    async def save(self, certificate: DepositCertificate) -> None: ...

    async def list_by_deposit(self, deposit_id: str) -> list[DepositCertificate]: ...

    async def list_by_tenant(self, tenant_id: str) -> list[DepositCertificate]: ...

    def next_certificate_number(self, tenant_id: str) -> str: ...


class IDepositStatementRepository(Protocol):
    async def save(self, statement: DepositStatement) -> None: ...

    async def list_by_deposit(self, deposit_id: str) -> list[DepositStatement]: ...

    def next_statement_ref(self, tenant_id: str) -> str: ...


class IDepositWorkflowRepository(Protocol):
    async def save(self, request: DepositWorkflowRequest) -> None: ...

    async def list_by_deposit(self, deposit_id: str) -> list[DepositWorkflowRequest]: ...


class IDepositAuditRepository(Protocol):
    async def save(self, entry: DepositAuditEntry) -> None: ...

    async def list_by_deposit(self, deposit_id: str) -> list[DepositAuditEntry]: ...
