"""Interest Calculation Engine repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.banking.domain.aggregates.interest_calculation_engine import (
    InterestCalculationAudit,
    InterestRateChange,
    InterestRateProfile,
)


class IInterestRateProfileRepository(Protocol):
    async def save(self, profile: InterestRateProfile) -> None: ...
    async def find_by_id(self, profile_id: str) -> InterestRateProfile | None: ...
    async def find_by_ref(self, tenant_id: str, profile_ref: str) -> InterestRateProfile | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[InterestRateProfile]: ...
    def next_profile_ref(self, tenant_id: str) -> str: ...


class IInterestRateChangeRepository(Protocol):
    async def save(self, change: InterestRateChange) -> None: ...
    async def list_by_profile(self, profile_id: str) -> list[InterestRateChange]: ...
    async def list_by_tenant(self, tenant_id: str) -> list[InterestRateChange]: ...


class IInterestCalculationAuditRepository(Protocol):
    async def save(self, audit: InterestCalculationAudit) -> None: ...
    async def find_by_id(self, audit_id: str) -> InterestCalculationAudit | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[InterestCalculationAudit]: ...
    async def list_by_profile(self, profile_id: str) -> list[InterestCalculationAudit]: ...
    async def list_by_source_ref(self, tenant_id: str, source_ref: str) -> list[InterestCalculationAudit]: ...
    def next_calc_ref(self, tenant_id: str) -> str: ...
