"""Enterprise KYC Platform repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.banking.domain.aggregates.kyc_platform_engine import (
    KycAddressVerification,
    KycAuditEntry,
    KycBiometricHook,
    KycCase,
    KycDocument,
    KycPeriodicReview,
    KycScreeningResult,
    KycWorkflowRequest,
)


class IKycCaseRepository(Protocol):
    async def save(self, case: KycCase) -> None: ...

    async def find_by_id(self, case_id: str) -> KycCase | None: ...

    async def find_by_ref(self, tenant_id: str, case_ref: str) -> KycCase | None: ...

    async def list_by_tenant(self, tenant_id: str) -> list[KycCase]: ...

    async def list_by_customer(self, customer_id: str) -> list[KycCase]: ...

    def next_case_ref(self, tenant_id: str) -> str: ...


class IKycDocumentRepository(Protocol):
    async def save(self, document: KycDocument) -> None: ...

    async def find_by_id(self, document_id: str) -> KycDocument | None: ...

    async def list_by_case(self, case_id: str) -> list[KycDocument]: ...

    async def list_by_tenant(self, tenant_id: str) -> list[KycDocument]: ...


class IKycAddressRepository(Protocol):
    async def save(self, address: KycAddressVerification) -> None: ...

    async def find_by_id(self, address_id: str) -> KycAddressVerification | None: ...

    async def list_by_case(self, case_id: str) -> list[KycAddressVerification]: ...


class IKycScreeningRepository(Protocol):
    async def save(self, result: KycScreeningResult) -> None: ...

    async def list_by_case(self, case_id: str) -> list[KycScreeningResult]: ...

    async def list_by_tenant(self, tenant_id: str) -> list[KycScreeningResult]: ...


class IKycReviewRepository(Protocol):
    async def save(self, review: KycPeriodicReview) -> None: ...

    async def find_by_id(self, review_id: str) -> KycPeriodicReview | None: ...

    async def list_by_case(self, case_id: str) -> list[KycPeriodicReview]: ...

    async def list_by_tenant(self, tenant_id: str) -> list[KycPeriodicReview]: ...

    def next_review_ref(self, tenant_id: str) -> str: ...


class IKycWorkflowRepository(Protocol):
    async def save(self, request: KycWorkflowRequest) -> None: ...

    async def list_by_case(self, case_id: str) -> list[KycWorkflowRequest]: ...


class IKycBiometricRepository(Protocol):
    async def save(self, hook: KycBiometricHook) -> None: ...

    async def find_by_id(self, hook_id: str) -> KycBiometricHook | None: ...

    async def list_by_case(self, case_id: str) -> list[KycBiometricHook]: ...


class IKycAuditRepository(Protocol):
    async def save(self, entry: KycAuditEntry) -> None: ...

    async def list_by_case(self, case_id: str) -> list[KycAuditEntry]: ...

    async def list_by_tenant(self, tenant_id: str) -> list[KycAuditEntry]: ...
