"""Loan Management repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.banking.domain.aggregates.loan_management_engine import (
    LoanAuditEntry,
    LoanCollateral,
    LoanCreditRiskAnalysis,
    LoanGuarantor,
    LoanInstallment,
    LoanProfile,
    LoanTransaction,
    LoanWorkflowRequest,
)


class ILoanProfileRepository(Protocol):
    async def save(self, loan: LoanProfile) -> None: ...
    async def find_by_id(self, loan_id: str) -> LoanProfile | None: ...
    async def find_by_account(self, account_id: str) -> LoanProfile | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[LoanProfile]: ...
    def next_loan_ref(self, tenant_id: str) -> str: ...


class ILoanCollateralRepository(Protocol):
    async def save(self, collateral: LoanCollateral) -> None: ...
    async def list_by_loan(self, loan_id: str) -> list[LoanCollateral]: ...


class ILoanGuarantorRepository(Protocol):
    async def save(self, guarantor: LoanGuarantor) -> None: ...
    async def list_by_loan(self, loan_id: str) -> list[LoanGuarantor]: ...


class ILoanInstallmentRepository(Protocol):
    async def save(self, installment: LoanInstallment) -> None: ...
    async def list_by_loan(self, loan_id: str) -> list[LoanInstallment]: ...
    async def find_by_id(self, installment_id: str) -> LoanInstallment | None: ...


class ILoanTransactionRepository(Protocol):
    async def save(self, transaction: LoanTransaction) -> None: ...
    async def find_by_id(self, transaction_id: str) -> LoanTransaction | None: ...
    async def list_by_loan(self, loan_id: str) -> list[LoanTransaction]: ...
    async def list_by_tenant(self, tenant_id: str) -> list[LoanTransaction]: ...
    def next_transaction_ref(self, tenant_id: str) -> str: ...


class ILoanCreditRiskRepository(Protocol):
    async def save(self, analysis: LoanCreditRiskAnalysis) -> None: ...
    async def find_by_loan(self, loan_id: str) -> LoanCreditRiskAnalysis | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[LoanCreditRiskAnalysis]: ...


class ILoanWorkflowRepository(Protocol):
    async def save(self, request: LoanWorkflowRequest) -> None: ...
    async def list_by_loan(self, loan_id: str) -> list[LoanWorkflowRequest]: ...


class ILoanAuditRepository(Protocol):
    async def save(self, entry: LoanAuditEntry) -> None: ...
    async def list_by_loan(self, loan_id: str) -> list[LoanAuditEntry]: ...
