"""Banking Payment Platform repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.banking.domain.aggregates.payment_platform_engine import (
    PaymentAuditEntry,
    PaymentBatch,
    PaymentBeneficiary,
    PaymentFraudCheck,
    PaymentTransfer,
    PaymentWorkflowRequest,
    StandingOrder,
)


class IPaymentBeneficiaryRepository(Protocol):
    async def save(self, beneficiary: PaymentBeneficiary) -> None: ...
    async def find_by_id(self, beneficiary_id: str) -> PaymentBeneficiary | None: ...
    async def list_by_customer(self, customer_id: str) -> list[PaymentBeneficiary]: ...
    async def list_by_tenant(self, tenant_id: str) -> list[PaymentBeneficiary]: ...
    def next_beneficiary_ref(self, tenant_id: str) -> str: ...


class IPaymentTransferRepository(Protocol):
    async def save(self, transfer: PaymentTransfer) -> None: ...
    async def find_by_id(self, transfer_id: str) -> PaymentTransfer | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[PaymentTransfer]: ...
    async def list_by_batch(self, batch_id: str) -> list[PaymentTransfer]: ...
    async def daily_total_by_account(self, tenant_id: str, account_id: str) -> float: ...
    async def velocity_count(self, tenant_id: str, customer_id: str, hours: int = 24) -> int: ...
    def next_transfer_ref(self, tenant_id: str) -> str: ...


class IPaymentBatchRepository(Protocol):
    async def save(self, batch: PaymentBatch) -> None: ...
    async def find_by_id(self, batch_id: str) -> PaymentBatch | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[PaymentBatch]: ...
    def next_batch_ref(self, tenant_id: str) -> str: ...


class IStandingOrderRepository(Protocol):
    async def save(self, order: StandingOrder) -> None: ...
    async def find_by_id(self, order_id: str) -> StandingOrder | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[StandingOrder]: ...
    def next_order_ref(self, tenant_id: str) -> str: ...


class IPaymentWorkflowRepository(Protocol):
    async def save(self, workflow: PaymentWorkflowRequest) -> None: ...
    async def list_by_transfer(self, transfer_id: str) -> list[PaymentWorkflowRequest]: ...


class IPaymentFraudRepository(Protocol):
    async def save(self, check: PaymentFraudCheck) -> None: ...
    async def find_by_transfer(self, transfer_id: str) -> PaymentFraudCheck | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[PaymentFraudCheck]: ...


class IPaymentAuditRepository(Protocol):
    async def save(self, entry: PaymentAuditEntry) -> None: ...
    async def list_by_transfer(self, transfer_id: str) -> list[PaymentAuditEntry]: ...
