"""Banking Settlement Engine repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.banking.domain.aggregates.settlement_engine import (
    BankReconciliationRun,
    ReconciliationMatch,
    SettlementAdjustment,
    SettlementAuditEntry,
    SettlementBatch,
    SettlementDifference,
    SettlementException,
    SettlementItem,
    SettlementReport,
)


class ISettlementBatchRepository(Protocol):
    async def save(self, batch: SettlementBatch) -> None: ...
    async def find_by_id(self, batch_id: str) -> SettlementBatch | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[SettlementBatch]: ...
    def next_batch_ref(self, tenant_id: str) -> str: ...


class ISettlementItemRepository(Protocol):
    async def save(self, item: SettlementItem) -> None: ...
    async def list_by_batch(self, batch_id: str) -> list[SettlementItem]: ...
    def next_item_ref(self, tenant_id: str) -> str: ...


class IReconciliationRunRepository(Protocol):
    async def save(self, run: BankReconciliationRun) -> None: ...
    async def find_by_id(self, run_id: str) -> BankReconciliationRun | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[BankReconciliationRun]: ...
    def next_run_ref(self, tenant_id: str) -> str: ...


class IReconciliationMatchRepository(Protocol):
    async def save(self, match: ReconciliationMatch) -> None: ...
    async def list_by_run(self, run_id: str) -> list[ReconciliationMatch]: ...


class ISettlementExceptionRepository(Protocol):
    async def save(self, exception: SettlementException) -> None: ...
    async def find_by_id(self, exception_id: str) -> SettlementException | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[SettlementException]: ...
    def next_exception_ref(self, tenant_id: str) -> str: ...


class ISettlementDifferenceRepository(Protocol):
    async def save(self, difference: SettlementDifference) -> None: ...
    async def list_by_run(self, run_id: str) -> list[SettlementDifference]: ...
    def next_difference_ref(self, tenant_id: str) -> str: ...


class ISettlementAdjustmentRepository(Protocol):
    async def save(self, adjustment: SettlementAdjustment) -> None: ...
    async def find_by_id(self, adjustment_id: str) -> SettlementAdjustment | None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[SettlementAdjustment]: ...
    def next_adjustment_ref(self, tenant_id: str) -> str: ...


class ISettlementAuditRepository(Protocol):
    async def save(self, entry: SettlementAuditEntry) -> None: ...
    async def list_by_source(self, source_type: str, source_id: str) -> list[SettlementAuditEntry]: ...


class ISettlementReportRepository(Protocol):
    async def save(self, report: SettlementReport) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[SettlementReport]: ...
    def next_report_ref(self, tenant_id: str) -> str: ...
