"""Identity lifecycle repository ports."""
from __future__ import annotations

from typing import Protocol

from contexts.identity_lifecycle.domain.aggregates.identity_lifecycle_platform import (
    ConsentRecord,
    LifecycleAuditEntry,
    LifecycleCase,
    LifecycleInvitation,
    LifecycleProfile,
    LifecycleTransition,
    VerificationTask,
)


class ILifecycleProfileRepository(Protocol):
    async def find_by_tenant(self, tenant_id: str) -> LifecycleProfile | None: ...
    async def save(self, profile: LifecycleProfile) -> None: ...
    def next_profile_ref(self, tenant_id: str) -> str: ...


class ILifecycleCaseRepository(Protocol):
    async def save(self, case: LifecycleCase) -> None: ...
    async def list_by_tenant(self, tenant_id: str) -> list[LifecycleCase]: ...
    async def find_by_ref(self, tenant_id: str, case_ref: str) -> LifecycleCase | None: ...
    def next_case_ref(self, tenant_id: str) -> str: ...


class ILifecycleTransitionRepository(Protocol):
    async def save(self, transition: LifecycleTransition) -> None: ...
    async def list_by_case(self, tenant_id: str, case_ref: str) -> list[LifecycleTransition]: ...
    def next_transition_ref(self, tenant_id: str) -> str: ...


class IVerificationTaskRepository(Protocol):
    async def save(self, task: VerificationTask) -> None: ...
    async def list_by_case(self, tenant_id: str, case_ref: str) -> list[VerificationTask]: ...
    async def find_by_ref(self, tenant_id: str, task_ref: str) -> VerificationTask | None: ...
    def next_task_ref(self, tenant_id: str) -> str: ...


class IConsentRecordRepository(Protocol):
    async def save(self, consent: ConsentRecord) -> None: ...
    async def list_by_case(self, tenant_id: str, case_ref: str) -> list[ConsentRecord]: ...
    def next_consent_ref(self, tenant_id: str) -> str: ...


class ILifecycleAuditRepository(Protocol):
    async def save(self, entry: LifecycleAuditEntry) -> None: ...
    async def list_by_case(self, tenant_id: str, case_ref: str) -> list[LifecycleAuditEntry]: ...
    async def list_by_tenant(self, tenant_id: str) -> list[LifecycleAuditEntry]: ...
    def next_audit_ref(self, tenant_id: str) -> str: ...


class ILifecycleInvitationRepository(Protocol):
    async def save(self, invitation: LifecycleInvitation) -> None: ...
    async def find_by_token(self, tenant_id: str, token: str) -> LifecycleInvitation | None: ...
    def next_invitation_ref(self, tenant_id: str) -> str: ...
